server:
  servlet:
    context-path: /matchboxv3
spring:
  datasource:
    url: ""
    username:
    password:
    driverClassName: org.postgresql.Driver

    # database connection pool size
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
matchbox:
  fhir:
    context:
      fhirVersion: 4.0.1
      txServer: http://tx.fhir.org
      onlyOneEngine: false
      httpReadOnly: true
hapi:
  fhir:
    # server_address: https://matchbox.apibox.ca/matchboxv3/fhir
    implementationguides:
      fhir_r4_core:
        name: hl7.fhir.r4.core
        version: 4.0.1
      fhir_terminology:
        name: hl7.terminology
        version: 5.4.0
      fhir_extensions:
        name: hl7.fhir.uv.extensions.r4
        version: 1.0.0
      fhir-baseline-1-1-8:
        name: hl7.fhir.ca.baseline
        version: 1.1.8
      hl7-fhir-extension-r4:
        name: hl7.fhir.uv.extensions.r4
        version: 5.1.0
      hl7-terminology-r4:
        name: hl7.terminology.r4
        version: 6.0.2
      psca-2-0-0-DFT-Ballot:
        name: ca.infoway.io.psca
        version: 2.0.0-DFT-Ballot
