spring:
  datasource:
    url: 'jdbc:h2:file:./target/database/h2'
    username: sa
    password: null
    driverClassName: org.h2.Driver
    max-active: 15
  jpa:
    properties:
#      hibernate.dialect: org.hibernate.dialect.h2dialect
#      hibernate.search.model_mapping: ca.uhn.fhir.jpa.search.lucenesearchmappingfactory
#      hibernate.format_sql: false
#      hibernate.show_sql: false
#      hibernate.hbm2ddl.auto: update
#      hibernate.jdbc.batch_size: 20
#      hibernate.cache.use_query_cache: false
#      hibernate.cache.use_second_level_cache: false
#      hibernate.cache.use_structured_entries: false
#      hibernate.cache.use_minimal_puts: false
#      hibernate.search.default.directory_provider: filesystem
#      hibernate.search.default.indexbase: target/lucenefiles
#      hibernate.search.lucene_version: lucene_current
  batch:
    job:
      enabled: false
server: 
  servlet:
    context-path: /hapi-fhir-jpavalidator
hapi:
  fhir:
    fhir_version: R4
    defer_indexing_for_codesystems_of_size: 0
    tester:
        home:
          name: Local Tester
          server_address: 'http://localhost:8080/fhir'
          refuse_to_fetch_third_party_urls: false
          fhir_version: R4
        global:
          name: Global Tester
          server_address: "http://hapi.fhir.org/baseR4"
          refuse_to_fetch_third_party_urls: false
          fhir_version: R4