server:
  servlet:
    context-path: /matchboxv3
matchbox:
  fhir:
    context:
      fhirVersion: 4.0.1
      txServer: http://tx.fhir.org
      onlyOneEngine: false
      httpReadOnly: true
hapi:
  fhir:
    server_address: https://matchbox.apibox.ca/matchboxv3/fhir
    implementationguides:
      psca:
        name: ca.infoway.io.psca
        version: 2.0.1-DFT-Ballot
        url: file:///home/echiu/Downloads/package.tgz
