server:
  servlet:
    context-path: /matchboxv3
spring:
  datasource:
    url: ''
    username: 
    password: 
    driverClassName: org.postgresql.Driver

    # database connection pool size
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
matchbox:
  fhir:
    context:
      fhirVersion: 4.0.1
      txServer: http://tx.fhir.org
      onlyOneEngine: false
      suppressWarnInfo:
        ca.infoway.io.erec:
          - "Constraint failed: dom-6:"
          - "regex:URL value '(.+)' does not resolve"
          - "regex:ValueSet '(.+)' not found"
          - "regex:This element does not match any known slice defined in the profile (.*)"
          - "regex:Reference to draft CodeSystem (.+)"
        ca.infoway.io.psca:
          - "Constraint failed: dom-6:"
          - "regex:URL value '(.+)' does not resolve"
          - "regex:ValueSet '(.+)' not found"
          - "regex:This element does not match any known slice defined in the profile (.*)"
          - "regex:Reference to draft CodeSystem (.+)"
          - "regex:A definition for CodeSystem '(.+)' could not be found, so the code cannot be validated"
          - "Best Practice Recommendation: In general, all observations should have a performer"
          - "Best Practice Recommendation: In general, all observations should have an effective[x] ()"
          - "regex:Validate Observation against (.+)"
          - "regex:Can't find '(.+)' in the bundle"
          - "regex:UCUM Codes that contain human readable annotations like (.+) can be misleading (.e.g. they are ignored when comparing units).(.+)"
          - "regex:A definition for the value Set '(.+)' could not be found"
          - "UNABLE_TO_CHECK_IF_THE_PROVIDED_CODES_ARE_IN_THE_VALUE_SET"
        ca.ab.fhir.psab:
          - "Constraint failed: dom-6:"
          - "regex:URL value '(.+)' does not resolve"
          - "regex:ValueSet '(.+)' not found"
          - "regex:This element does not match any known slice defined in the profile (.*)"
          - "regex:Reference to draft CodeSystem (.+)"
          - "regex:A definition for CodeSystem '(.+)' could not be found, so the code cannot be validated"
          - "Best Practice Recommendation: In general, all observations should have a performer"
          - "Best Practice Recommendation: In general, all observations should have an effective[x] ()"
          - "regex:Validate Observation against (.+)"
          - "regex:Can't find '(.+)' in the bundle"
          - "regex:UCUM Codes that contain human readable annotations like (.+) can be misleading (.e.g. they are ignored when comparing units).(.+)"
          - "regex:A definition for the value Set '(.+)' could not be found"
          - "UNABLE_TO_CHECK_IF_THE_PROVIDED_CODES_ARE_IN_THE_VALUE_SET"
        ca.on.oh.patient-summary:
          - "Constraint failed: dom-6:"
          - "regex:URL value '(.+)' does not resolve"
          - "regex:ValueSet '(.+)' not found"
          - "regex:This element does not match any known slice defined in the profile (.*)"
          - "regex:Reference to draft CodeSystem (.+)"
          - "regex:A definition for CodeSystem '(.+)' could not be found, so the code cannot be validated"
          - "Best Practice Recommendation: In general, all observations should have a performer"
          - "Best Practice Recommendation: In general, all observations should have an effective[x] ()"
          - "regex:Validate Observation against (.+)"
          - "regex:Can't find '(.+)' in the bundle"
          - "regex:UCUM Codes that contain human readable annotations like (.+) can be misleading (.e.g. they are ignored when comparing units).(.+)"
          - "regex:A definition for the value Set '(.+)' could not be found"
          - "UNABLE_TO_CHECK_IF_THE_PROVIDED_CODES_ARE_IN_THE_VALUE_SET"
      httpReadOnly: true
hapi:
  fhir:
    server_address: https://matchbox.apibox.ca/matchboxv3/fhir
    implementationguides:
      fhir_r4_core:
        name: hl7.fhir.r4.core
        version: 4.0.1
      fhir_terminology:
        name: hl7.terminology
        version: 5.4.0
      fhir_extensions:
        name: hl7.fhir.uv.extensions.r4
        version: 1.0.0
      fhir-baseline-1-1-8:
        name: hl7.fhir.ca.baseline
        version: 1.1.8
      hl7-fhir-extension-r4:
        name: hl7.fhir.uv.extensions.r4
        version: 5.1.0
      hl7-terminology-r4:
        name: hl7.terminology.r4
        version: 6.0.2
      ips110:
        name: hl7.fhir.uv.ips
        version: 1.1.0
      ips200bt:
        name: hl7.fhir.uv.ips
        version: 2.0.0-ballot
      mhd422:
        name: ihe.iti.mhd
        version: 4.2.2
      mhd410:
        name: ihe.iti.mhd
        version: 4.1.0
      pixm300:
        name: ihe.iti.pixm
        version: 3.0.0
      pdqm300:
        name: ihe.iti.pdqm
        version: 3.0.0
      pmir150:
        name: ihe.iti.pmir
        version: 1.5.0
      psca:
        name: ca.infoway.io.psca
        version: 2.0.0-DFT-Ballot
      psab:
        name: ca.ab.fhir.psab
        version: 1.1.0
      pson:
        name: ca.on.oh.patient-summary
        version: 0.11.0
      erec:
        name: ca.infoway.io.erec
        version: 1.0.3-dft-projectathon
      erec-on:
        name: ca.on.oh-eReferral-eConsult
        version: 0.12.0-alpha1.0.7
        url: file:///home/echiu/Downloads/ca.on.oh-ereferral-econsult-0.12.0-alpha1.0.7-snapshots.tgz
      cafex210:
        name: ca.infoway.io.cafex
        version: 2.1.0-DFT-preBallot
      cabase118:
        name: hl7.fhir.ca.baseline
        version: 1.1.8
      uscore610:
        name: hl7.fhir.us.core
        version: 6.1.0
      bulkdata200:
        name: hl7.fhir.uv.bulkdata
        version: 2.0.0
      ipa100:
        name: hl7.fhir.uv.ipa
        version: 1.0.0
      sdc300:
        name: hl7.fhir.uv.sdc
        version: 3.0.0
      smart210:
        name: hl7.fhir.uv.smart-app-launch
        version: 2.1.0
      term540:
        name: hl7.terminology
        version: 5.4.0
      format120:
        name: ihe.formatcode.fhir
        version: 1.2.0
      balp113:
        name: ihe.iti.balp
        version: 1.1.3
      phinvads0120:
        name: us.cdc.phinvads
        version: 0.12.0
      vsac0110:
        name: us.nlm.vsac
        version: 0.11.0
