# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - "charts/**"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "charts/**"

jobs:
  build:

    runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-java@v3
    with:
      java-version: '11'
      distribution: 'adopt'
      cache: 'maven'
  - run: mvn --batch-mode --update-snapshots verify
  - uses: actions/upload-artifact@v3
    with:
      name: Package
      path: staging