# This workflow will build a Java project with Maven
name: Java CI with Maven

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - "charts/**"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "charts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp matchbox-engine/target/*.jar staging && cp matchbox-server/target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging