# Those are reusable workflows, they don't trigger on their own
# https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
  workflow_call:

jobs:
  setup_java:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java 20
        uses: actions/setup-java@v3
        # https://github.com/actions/setup-java#usage
        with:
          java-version: "20"
          distribution: "adopt"
          cache: "maven"

      - name: Compile
        run: mvn --batch-mode --no-transfer-progress --update-snapshots -DskipTests compile
        working-directory: matchbox
